; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
lib_archive = false
monitor_speed = 115200

lib_deps = 	
	; knolleary/PubSubClient@^2.8
	tzapu/WiFiManager@^2.0.17
	; plapointe6/EspMQTTClient@^1.13.3
	; cyijun/ESP32MQTTClient@^1.0.0
    
	; This library (https://github.com/khoih-prog/AsyncMQTT_ESP32.git) adds dependency to all the boards that will not work in platformio.
	; So needed to fork this and edited library.json 
	; Using the forked one instead
	https://github.com/ACI-MIS-Team/AsyncMQTT_ESP32.git
	
	; Librarys for audio
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/pschatzmann/arduino-libhelix.git
